# Data Cleaning Challenge

**Name:** Ayushi Tyagi  
**Project:** Customer Data Cleaning  
**Tools:** Python, Pandas

## Objective
To clean and prepare customer data by handling missing values, duplicates, incorrect data types, and inconsistent data.

In [2]:
#Import Pandas
import pandas as pd

In [3]:
#Load the dataset
df = pd.read_csv("messy_customer_data.csv")

In [4]:
# Display the first 5 rows
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [5]:
# Check the dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          7621 non-null   object
 1   Name                8342 non-null   object
 2   Gender              7545 non-null   object
 3   Age                 7424 non-null   float64
 4   City                8870 non-null   object
 5   Signup_Date         7471 non-null   object
 6   Last_purchase_date  6714 non-null   object
 7   purchase_amount     4967 non-null   float64
 8   feedback_score      7538 non-null   float64
 9   email               4934 non-null   object
 10  Phone_number        7556 non-null   object
 11  Country             8296 non-null   object
dtypes: float64(3), object(9)
memory usage: 937.6+ KB

In [6]:
# Check the number of rows and columns
df.shape

(10000, 12)

In [7]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [9]:
#Check for duplicated rows
df.duplicated().sum()

np.int64(0)

In [10]:
# Remove duplicate rows
df = df.drop_duplicates()

# Check duplicates again
df.duplicated().sum()

np.int64(0)

In [11]:
# Fill missing values in numerical columns with the median
df = df.fillna(df.median(numeric_only=True))

In [12]:
# Check if missing values remain
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                      0
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount          0
feedback_score           0
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [13]:
# Check the data types of each column
df.dtypes

CustomerID             object
Name                   object
Gender                 object
Age                   float64
City                   object
Signup_Date            object
Last_purchase_date     object
purchase_amount       float64
feedback_score        float64
email                  object
Phone_number           object
Country                object
dtype: object

In [16]:
# Convert date columns to datetime format
df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce")
df["Last_purchase_date"] = pd.to_datetime(df["Last_purchase_date"], errors="coerce")

C:\Users\ACER\AppData\Local\Temp\ipykernel_27008\2934268287.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce")
C:\Users\ACER\AppData\Local\Temp\ipykernel_27008\2934268287.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Last_purchase_date"] = pd.to_datetime(df["Last_purchase_date"], errors="coerce")

In [17]:
# Check the date column data types
df[["Signup_Date", "Last_purchase_date"]].dtypes

Signup_Date           datetime64[ns]
Last_purchase_date    datetime64[ns]
dtype: object

In [18]:
# Check for invalid or missing dates
df[["Signup_Date", "Last_purchase_date"]].isnull().sum()

Signup_Date           5004
Last_purchase_date    6652
dtype: int64

In [19]:
# Remove extra spaces from text columns
text_columns = ["Name", "Gender", "City", "email", "Phone_number", "Country"]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [20]:
# Display the cleaned dataset
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,2024-12-31,2025-08-13,-999.0,2.0,nan,0,Canada
1,C2,Ravi,Female,43.0,Kolkata,NaT,NaT,-999.0,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaT,2023-06-20,-999.0,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaT,2025-09-13,-999.0,3.0,nan,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,2025-07-09,NaT,-999.0,3.0,user4mail.com,9234603292,USA

In [21]:
# Check the final shape of the cleaned dataset
df.shape

(10000, 12)

In [22]:
# Remove personal contact information before publishing
df_cleaned = df.drop(columns=["email", "Phone_number"])

df_cleaned.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,Country
0,NaN,Ankit,F,36.0,Mumbai,2024-12-31,2025-08-13,-999.0,2.0,Canada
1,C2,Ravi,Female,43.0,Kolkata,NaT,NaT,-999.0,-1.0,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaT,2023-06-20,-999.0,10.0,India
3,C4,Ankit,male,44.0,Kolkata,NaT,2025-09-13,-999.0,3.0,USA
4,5,Rahul,Male,200.0,Ahmedabad,2025-07-09,NaT,-999.0,3.0,USA

In [23]:
# Save the cleaned dataset
df_cleaned.to_csv("cleaned_customer_data.csv", index=False)

# Conclusion

The customer dataset was cleaned by:

- Removing duplicate records
- Handling missing values
- Converting date columns to the correct format
- Cleaning text values and removing extra spaces
- Removing personal contact information from the publishable dataset

The cleaned dataset is now ready for further analysis.